### ISSUE TITLE
watchdog: timeout while getting file from github

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet-tools#1]
@lewismc @abburgess @graybeal FYI

Just noted that our watchdog cronjob recently failed due a timeout while trying to get a file from github (see below).

Not critical at all as the cronjob will just be re-run at the next scheduled time. But a possible adjustment is to simply report a timeout message and exit the script.

----
(Cron <cor-admin1@ip-172-30-0-37> cd /home/cor-admin1/sweet-tools/sc/watchdog/ && ./watchdog.sc update >> watchdog.cronjob.out)

```
java.net.SocketTimeoutException: Read timed out
  ...
  scalaj.http.HttpRequest.doConnection(Http.scala:359)
  scalaj.http.HttpRequest.exec(Http.scala:335)
  scalaj.http.HttpRequest.asString(Http.scala:455)
  ammonite.$file.github$Github$.getFile(github.sc:38)
  ammonite.$file.watchdog$.$anonfun$getGithubInfo$1(watchdog.sc:148)
  ...
```

**Comment by lewismc** [comment]
+1 for notification this can be established with the cron correct?

**Comment by carueda** [comment]
This is rather old, not happening anymore AFAICT, and not serious anyway.
