### ISSUE TITLE
sweetontology.net still resolving to previous amazon instance

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet-tools#6]
It's still resolving to ec2-34-216-150-176.us-west-2.compute.amazonaws.com !

This has caused some headaches already  ; )

(Was not sure where to enter this issue, but didn't want to do it under /sweet as that's more for the semantic contents...)

**Comment by lewismc** [comment]
The action here is for Annie Burgess.

**Comment by lewismc** [comment]
@carueda was the old machine NOT switched off? If so then we should plan to decommission it.

**Comment by carueda** [comment]
@lewismc  You are welcome to update `/etc/httpd/conf.d/sweetontology.conf` on the new machine based on the version I updated today on the old one (or I can do that if you or Annie can tell me in advance when you guys will be decommissioning the old one)

**Comment by carueda** [comment]
As noted on Slack, I just copied `/etc/httpd/conf.d/sweetontology.conf` to `ec2-54-190-88-51.us-west-2.compute.amazonaws.com` (and restarted apache there), so all should be in place whenever you guys decide to update the DNS settings for `sweetontology.net`.

**Comment by carueda** [comment]
Thanks Annie.
